GET http://localhost:3000/posts
Authorization: Bearer KEY-HERE

###

DELETE http://localhost:4000/logout Content-Type: application/json

{
"token": "TOKEN HERE"
}

###

POST http://localhost:4000/token Content-Type: application/json

{
"token": "TOKEN HERE"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Kyle"
}
